---
apiVersion: v1
kind: Service
metadata:
  name: ha
  namespace: networking
  labels:
    app.kubernetes.io/name: ha
    app.kubernetes.io/instance: ha
spec:
  type: ExternalName
  externalName: ha.
  ports:
    - name: http
      port: &port 8443
      protocol: TCP
      targetPort: *port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ha
  namespace: networking
  annotations:
    external-dns.alpha.kubernetes.io/target: "vip2.${SECRET_EXTERNAL_DOMAIN}"
    hajimari.io/icon: video-input-antenna
  labels:
    app.kubernetes.io/name: ha
    app.kubernetes.io/instance: ha
spec:
  ingressClassName: nginx
  rules:
    - host: &host ha.${SECRET_EXTERNAL_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ha
                port:
                  number: 8123
  tls:
    - hosts:
        - *host
