---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./download-pvc.yaml
  - ./overseerr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./tautulli/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./doplarr/ks.yaml
  - ./plex/ks.yaml
  - ./wizarr/ks.yaml
  - ./calibre-web/ks.yaml
  - ./calibre/ks.yaml
  - ./readarr/ks.yaml
  - /qbit/ks.yaml
