---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./external-dns.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./prometheus-community.yaml
  - ./stakater.yaml
  - ./weave-gitops.yaml
  - ./rook-ceph.yaml
  - ./jupyterhub-charts.yaml
  - ./prometheus-community-charts.yaml
  - ./valheim-charts.yaml
  - ./k8s-at-home-charts.yaml
  - ./zalando-postgres-operator.yaml
  - ./backube.yaml
  - ./piraeus.yaml
  - ./intel.yaml
  - ./node-feature-discovery.yaml
  - ./kyverno-charts.yaml
  - ./longhorn-charts.yaml
  - ./angelnu.yaml
  - ./cloudnative-pg.yaml
  - ./itzg-minecraft-server-charts.yaml
