---
kubernetes:
  children:
    master:
      hosts:
        k3s-0:
          ansible_host: 192.168.10.40
        k3s-1:
          ansible_host: 192.168.10.41
        k3s-2:
          ansible_host: 192.168.10.42
    worker:
      hosts:
        k3s-3:
          ansible_host: 192.168.10.43
          rook_block_devices: 
            - /dev/disk/by-id/nvme-INTEL_SSDPEKNW010T8_BTNH10260EF71P0B
        k3s-4:
          ansible_host: 192.168.10.44
          rook_block_devices: 
            - /dev/disk/by-id/nvme-INTEL_SSDPEKNW010T8_BTNH11760J621P0B
        k3s-5:
          ansible_host: 192.168.10.45
          rook_block_devices: 
            - /dev/disk/by-id/nvme-INTEL_SSDPEKNW010T8_BTNH117623RB1P0B
