kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: radarr-restic-secret
    namespace: media
stringData:
    B2_ACCOUNT_ID: ENC[AES256_GCM,data:U7/7WKhFJAqE7iv1VpO3aMkjJEA/ltVMWg==,iv:klnr0GbmrBu4pNyjfLrWQQlJGcT0ao/ddM49Ji49fGg=,tag:nwqpdszdDaEP4DAaISR/Iw==,type:str]
    B2_ACCOUNT_KEY: ENC[AES256_GCM,data:9Dt+CdPHg2up4xj4qqRn53+lXJx4MAETjDY29IkKRQ==,iv:Xh8ItWQfJhTxQZVrtASfKUkfwH7oagNzA2IRDM2HtLQ=,tag:CvVH4VvBOwikW7OKpBk/Uw==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:fNYGKLSavR3s2vHgO5qm,iv:3nrN0q59rHV8i9aFm1PCF28xYVNpO2/mbSwMJeaoprs=,tag:UGtqhPpAEQDqW/ScR3rSog==,type:str]
    #ENC[AES256_GCM,data:gMHhGOIXFrhrAYGdeufyEAv8hSUJ6DYvzBRL6xo5ElCHyyBc8Ff48FQoJQGZ89RQZ5xEciUsxOVvaSAOPC7wn8hgBK3hGSn9OZaXTIgvXYp/OKM=,iv:6ULB0DEtAmN++U3EEFpW7RKNzbU0ggQLWH+GIlVKEXg=,tag:35c7AMEz7upCAdPz3Es7Gg==,type:comment]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:PMqAVm9vvOSL55o=,iv:4mzCOOCzM4lhSXCf6Cb1vcjQt4FGb11xMOksZ0ef1CU=,tag:E1mgrQgbbTB8OflnQ19J7A==,type:str]
#    AWS_ACCESS_KEY_ID: 002af3077ab7123000000000a
#    AWS_SECRET_ACCESS_KEY: K002UYJxapslRsxEmBD0V86iTqHVI1w
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia2NIQXpYYUUvQmd1eW44
            Z0tQeGZxUjFPa0ZzQlB5MjM0TVlONGVxZ2dJCklJNUxtQjhPakliV0hJYXJ2WVFa
            TkdaK0lwdlRiUm9HSU9ZUlE0MXNIWjgKLS0tIDhJQXBicUQzSTdpN2FCUHVZVllk
            THp2bDdOdGg4S2ZscUtScHZLdmgyRDgKt1u3LByLvqiFtfb24QMQhZo7OQLdV1yS
            YK0Vg4nS79WWqji1TjZL5I1j6LKvnEsNoGOlOhE4W5TkDxfac1rb4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-10T23:57:39Z"
    mac: ENC[AES256_GCM,data:0Kqsv5VAyq63vyT57qtHYPkLdgLd5thHytQbY/2+iBT8ML238nzKZ8jwfmcILYbsrm2DlE5UlVDAsNpqVY9Ds4PtaysB6UiulHZBQugGQ/ecfFcqvy1o2lnPAYTVfOiNceFwl33m08cGwhXqAH3ojwDvIotqmXdCwZa3Bc6gTEE=,iv:+/OMciL1kDa91nx6di7G+GrjL5KIXrsstiSm0FQrCBk=,tag:VoXPlgS/g6SK5UgHJg/nJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
