apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:8AI84+HnCEAvewRH,iv:JfeilUCFUqgRXq98hQvsXbHIg6xFXDZZLP0ZWS0R3d4=,tag:TWC9Gbcq3COhJ/TzqE2dJQ==,type:str]
    SECRET_EXTERNAL_DOMAIN: ENC[AES256_GCM,data:Z5kg+ej6pjhfFEk=,iv:6HqB1Asy9uCvtmliryM9HRRgD3M13P+OOAKd3rP7C5g=,tag:0WZ/VMV2ZqdFrHqwaXx8GA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:mpgcR+UxtNgISh8yS+8MtnQ=,iv:BRcsdjBAaWbNQnXWQcrMjcsVPDrZTuud9RAR3fzeQzI=,tag:3WmMIsxyF9ni5Taclt3r5Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:xx3kpKD1si188fooQHjuxwdtVYEsY9GbGqHN6VuOGFLMZ2bT,iv:BRFBPMEFj7ZdnqOM29Qa1elEAkgdEsAb8KuY8h9zi2Y=,tag:BXWRjEQoXJnkZ8Rw+q8euA==,type:str]
    SECRET_PLEX_TOKEN: ENC[AES256_GCM,data:BtOg6W1yi4SzTdSg26gGa8s8UUk=,iv:cUD32l0667a+4VRfMBaBZmlabWACVze/LwvWGizAUPA=,tag:8hlyWvJHNFWI4t70M7wDcQ==,type:str]
    SECRET_PROWLARR_KEY: ENC[AES256_GCM,data:tNQ7SUgfS3Su5n9Zi/0lHBdd4Uy9SuQsw05i2k73Uvg=,iv:MxKA4VTjlEjInOgx50v4GCmei2EkC3O2OM3KpnBHszc=,tag:Pgf8hw39fBKEffWUa5lx+Q==,type:str]
    SECRET_RADARR_KEY: ENC[AES256_GCM,data:+tsFsEeYovH66J7kHOFPuqj+MgALCjr3VfZt8PW5nGE=,iv:9JRwdPMgYyoCKY1+i2dA3qmFr1Q/5L3KWryHTTj3kOQ=,tag:mCNXA+Oy5Q76ymttuqlU/Q==,type:str]
    SECRET_SONARR_KEY: ENC[AES256_GCM,data:Pfg0wRqFCIdbuJgQxNI7sP7qQb25+3PMnF5oSljGQMc=,iv:vUUmD1kfyQq8nj2DniSS6Ao5XkUKWgJoUvcTBlTnQC0=,tag:2FtWvnPMLQKnD1NmAG8Lgg==,type:str]
    SECRET_OVERSEERR_KEY: ENC[AES256_GCM,data:q+a0Il3XSgIXdN8aleWxKBBapYW6rXGakqDEnptMeNXyfRJnNW9AnaVd9MlNYBPqlX8JIebwu3WSIpttp0rsDnjgYyo=,iv:0bYfU69LSQ957MBAXOX7Jho4hdFsqzKq8w0PXfaWNFE=,tag:AuR3VyAMJSqs2oZetQzQbQ==,type:str]
    SECRET_DOPLARR_TOKEN: ENC[AES256_GCM,data:fDdTl5ooDepIVnLPW0gHRlJCExP7SxTxRykfyLqXTEQoUspjUuTEJKi5Mih15U1iS0h++szg+2DxRrE=,iv:IYaEdPHtCeIdlHIoxaLZLb5WLkABXUJpwZWcqRCTmkA=,tag:ZRn2pZIffNDeGxBjDh1uLg==,type:str]
    NAS: ENC[AES256_GCM,data:FWdux4/224oX+5Pspg==,iv:WY4ra8EktxxVtjOpexEeFZQoCkREFwkzcWHS3z7AFwE=,tag:/9q3xlVRKxphPcu4Tdhokg==,type:str]
    FRANK: ENC[AES256_GCM,data:k5BUkQHU8fW6nXLS,iv:xAugjX9CECIVO69JnNTuax+ib295yNVoCGKBRgOoziY=,tag:8tvenzAUjWilJON+MkuxoA==,type:str]
    POSTGRES_PRINTER_PASSWORD: ENC[AES256_GCM,data:X9/5YjFim70TXkw=,iv:6lUwBXY+Pr0mrDvnqbSZI+kHcUOIcXknPxYeS3HZxc4=,tag:XT45c9RaoRJmwE0EDscPFA==,type:str]
    POSTGRES_ADMIN_PASSWORD: ENC[AES256_GCM,data:L68LR86iFLbnrSg=,iv:rVMIxr0caVVMz+b6L8N1egAzfjWQ96dyaKXIDjrFoT4=,tag:H62sSJKlwIBvMQkca/rZzQ==,type:str]
    SVC_POSTGRES_ADDR: ENC[AES256_GCM,data:D5W+C2SFlvu/FgywIw==,iv:biXFJV5qcGCrdkV8kS/axUxD3raDBeUlZOfR1WfkXf0=,tag:rEC/RW9lJR00M99eXbaRSA==,type:str]
    SVC_SCRYPTED_ADDR: ENC[AES256_GCM,data:yjt4slwwHUHAdKWN/Q==,iv:ONxiri45vxF88kr76a14rt6iqk1LVtsEAUcSv0/M/YE=,tag:S9mgPuuByh2iRl4t/l2Hlg==,type:str]
    SVC_POSTGRESDB_ADDR: ENC[AES256_GCM,data:pUTAFujh/NLRt7c7Dg==,iv:Eeflid7DQmcTeUygbtQ8liT5T080Wv+6ajWkEkNmmUE=,tag:LVjnIkiDQm7U5vc9VNUZEg==,type:str]
    SVC_MQTT_ADDR: ENC[AES256_GCM,data:dNvm1zbVXYJFJVmhOQ==,iv:7OcX0SbQF99tpAlFFpLHysEL+nguJxaJJw0+EKbwrrg=,tag:PhrYXXvorPAyc/W3eRH5FQ==,type:str]
    SVC_PLEX_ADDR: ENC[AES256_GCM,data:14wEWqP/oAaidFv8Kg==,iv:WU4to1Z78NJc1791BKSq/JvGtEI3u6C3z7gb2czlkiA=,tag:TkZJUEwuqDsSkmaS/bEtPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdUJkMFI0TEF4NzZNQW9E
            SUlOeFpXK0ltTWs2VmRBdjQxOTV5WUMwYng0CndyZm9OaGFuRUFFbkdaVTVaQkMz
            anJaNXVlcUE1UG5wUTc2SXVCekM1YWMKLS0tIEpaaDV5ekFXRVNJbFJTQlRkUzgr
            TnBzbGlFVTNRcm00RDVBTEVkZEVxS3cKqd5baE7gnLnOPY3n4qRwWdtjcEw+B3q4
            C4c0RRnfpa7fO5aulEkJQYD94FIUSjz2bfDdHy04CiDFiUsrOKMYuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-10T03:07:14Z"
    mac: ENC[AES256_GCM,data:cFBla75EQrvyEiwrEFlNpA1ICwXJgF4AbjOqzc91GKm0ATofFY0tn8aOuqh/3LNIGhlfbHZ79DlLlu8B9TV2kVPbr0MuGfHz7HxAFVv8rU5qtbJG9s38oLp4Fqeezex1IzSz8FfMCe0uy/z/TyIXMbxSYMqW1SvqkO24SgSRJSc=,iv:8GSLZnMHewyUHlWENiR6enfqzuht8Cyzs0MO07J0PSg=,tag:9100TkRx5DuHvDQ05xT+tg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
