apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:8AI84+HnCEAvewRH,iv:JfeilUCFUqgRXq98hQvsXbHIg6xFXDZZLP0ZWS0R3d4=,tag:TWC9Gbcq3COhJ/TzqE2dJQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:mpgcR+UxtNgISh8yS+8MtnQ=,iv:BRcsdjBAaWbNQnXWQcrMjcsVPDrZTuud9RAR3fzeQzI=,tag:3WmMIsxyF9ni5Taclt3r5Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:xx3kpKD1si188fooQHjuxwdtVYEsY9GbGqHN6VuOGFLMZ2bT,iv:BRFBPMEFj7ZdnqOM29Qa1elEAkgdEsAb8KuY8h9zi2Y=,tag:BXWRjEQoXJnkZ8Rw+q8euA==,type:str]
    POSTGRES_PRINTER_PASSWORD: ENC[AES256_GCM,data:X9/5YjFim70TXkw=,iv:6lUwBXY+Pr0mrDvnqbSZI+kHcUOIcXknPxYeS3HZxc4=,tag:XT45c9RaoRJmwE0EDscPFA==,type:str]
    POSTGRES_ADMIN_PASSWORD: ENC[AES256_GCM,data:L68LR86iFLbnrSg=,iv:rVMIxr0caVVMz+b6L8N1egAzfjWQ96dyaKXIDjrFoT4=,tag:H62sSJKlwIBvMQkca/rZzQ==,type:str]
    SVC_POSTGRES_ADDR: ENC[AES256_GCM,data:D5W+C2SFlvu/FgywIw==,iv:biXFJV5qcGCrdkV8kS/axUxD3raDBeUlZOfR1WfkXf0=,tag:rEC/RW9lJR00M99eXbaRSA==,type:str]
    SVC_SCRYPTED_ADDR: ENC[AES256_GCM,data:yjt4slwwHUHAdKWN/Q==,iv:ONxiri45vxF88kr76a14rt6iqk1LVtsEAUcSv0/M/YE=,tag:S9mgPuuByh2iRl4t/l2Hlg==,type:str]
    SVC_POSTGRESDB_ADDR: ENC[AES256_GCM,data:pUTAFujh/NLRt7c7Dg==,iv:Eeflid7DQmcTeUygbtQ8liT5T080Wv+6ajWkEkNmmUE=,tag:LVjnIkiDQm7U5vc9VNUZEg==,type:str]
    SVC_MQTT_ADDR: ENC[AES256_GCM,data:dNvm1zbVXYJFJVmhOQ==,iv:7OcX0SbQF99tpAlFFpLHysEL+nguJxaJJw0+EKbwrrg=,tag:PhrYXXvorPAyc/W3eRH5FQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:EpyinhqHnI5hRdplEvxEHA==,iv:nK/fTM/+C4XlSxWuJOpV2cdYzsUW1MjHFgVh8YZnfUg=,tag:nbMNfa8M5G9lILBNiL63/g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:H7B5LMy1iePksKM=,iv:RqazaFRzVLkELVGT0b8Xbt2ScEqsc4oPViEaMWSaGsw=,tag:j9NSaBWZnYNTF+K435eT3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdUJkMFI0TEF4NzZNQW9E
            SUlOeFpXK0ltTWs2VmRBdjQxOTV5WUMwYng0CndyZm9OaGFuRUFFbkdaVTVaQkMz
            anJaNXVlcUE1UG5wUTc2SXVCekM1YWMKLS0tIEpaaDV5ekFXRVNJbFJTQlRkUzgr
            TnBzbGlFVTNRcm00RDVBTEVkZEVxS3cKqd5baE7gnLnOPY3n4qRwWdtjcEw+B3q4
            C4c0RRnfpa7fO5aulEkJQYD94FIUSjz2bfDdHy04CiDFiUsrOKMYuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-08T00:33:25Z"
    mac: ENC[AES256_GCM,data:DrxT9sA4jvbg/6mMQw9+gJyaXhOBZXgeEG0cI+I6GNwDTp13Ea+rstLvS3dSwDN0CJibgTOONPgSl/D0UyCFjxjScK0IQ0fNw9NZGiFA8Km3YWCqaGjBlvJ15aFjSpDrxknHTFch4Tw3SoI9AF7rnQiczMMMQPdifm6eEyK+iTM=,iv:+zQVpGmpXcTj1LxjmGCLtQzPuVJoFqgf13f4Q41teoY=,tag:EWkGzydgTAYP438zt9fAgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
