---
collections:
  - name: community.general
    version: 9.0.1
  - name: community.sops
    version: 1.6.4
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 2.10.3
  - name: kubernetes.core
    version: 4.0.0
roles:
  - name: githubixx.cilium_cli
    version: 2.8.0+0.16.4
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.4.2
